[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
packrun = "Hj9xusyzfxP8ic9U6rmpGcY4pPGFBJQqm7BUJ4w475jU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/packrun.test.mjs"
